import { getAiResponse, getAvailableProviders, specialistRoles, getAI } from '../config/ai.js'
import { webSearch, fetchPage, looksTimeSensitive, searchImages, searchForVerification } from '../../lib/webSearch.js'
import { generateImage } from './imageService.js'
import { query } from '../../lib/db.js'
import { randomUUID } from 'crypto'

// Verification system: extracts claims, searches web, revises with citations
const CLAIM_CACHE = new Map()
const CACHE_TTL = 60 * 60 * 1000 // 1 hour

// Full-answer cache: keyed on normalized question. Skips the full council pipeline
// (25+ provider calls, 3 rounds) when the same question is asked again — common
// across students in the same course.
const ANSWER_CACHE = new Map()
const ANSWER_CACHE_TTL = 6 * 60 * 60 * 1000 // 6 hours
const ANSWER_CACHE_MAX_SIZE = 500

function normalizeForCache(text) {
  return (text || '').toLowerCase().trim().replace(/\s+/g, ' ').replace(/[^\w\s]/g, '')
}

function buildCacheKey(messages, { turboMode, jsonMode }) {
  const userTurns = messages.filter(m => m.role === 'user')
  if (userTurns.length !== 1) return null
  const normalized = normalizeForCache(userTurns[0].content)
  if (!normalized || normalized.length < 3) return null
  return `${turboMode ? 'turbo' : 'council'}:${jsonMode ? 'json' : 'text'}:${normalized}`
}

function getCachedAnswer(key) {
  if (!key) return null
  const entry = ANSWER_CACHE.get(key)
  if (!entry) return null
  if (Date.now() - entry.ts > ANSWER_CACHE_TTL) {
    ANSWER_CACHE.delete(key)
    return null
  }
  return entry.data
}

function setCachedAnswer(key, data) {
  if (!key) return
  if (ANSWER_CACHE.size >= ANSWER_CACHE_MAX_SIZE) {
    const oldestKey = ANSWER_CACHE.keys().next().value
    ANSWER_CACHE.delete(oldestKey)
  }
  ANSWER_CACHE.set(key, { data, ts: Date.now() })
}

function formatForCitation(rawResult, index) {
  let domain = 'unknown'
  try {
    if (rawResult.url && rawResult.url.startsWith('http')) {
      domain = new URL(rawResult.url).hostname.replace('www.', '')
    }
  } catch {}
  return {
    citationId: index + 1,
    title: rawResult.title || 'Untitled',
    snippet: rawResult.snippet || '',
    url: rawResult.url || '',
    domain,
    authoritative: isAuthoritativeDomain(rawResult.url || '')
  }
}

async function extractClaims(draftAnswer) {
  const prompt = `Extract 3-5 specific, verifiable claims from this answer.
Return ONLY a JSON array of strings. Each claim must be a complete, fact-checkable sentence.
Focus on: numbers, dates, names, "latest/current/best", comparisons, statistics, "first/most", proper nouns.

Answer: ${draftAnswer}`
  
  const providers = getWorkingProviders()
  const fast = providers.find(p => ['groq', 'openrouter'].includes(p)) || providers[0]
  const resp = await getAiResponseWithTimeout(fast, [{role: 'user', content: prompt}], {temperature: 0.1, json: true}, 5000)
  if (resp) {
    try { return JSON.parse(resp) } catch {}
  }
  return []
}

async function reviseWithCitations(draftAnswer, verifiedClaims, messages) {
  const sysContent = messages.find(m => m.role === 'system')?.content || ''
  const allSources = []
  for (const vc of verifiedClaims) {
    for (const s of (vc.sources || [])) {
      if (!allSources.find(x => x.url === s.url)) allSources.push(s)
    }
  }
  const sourcesBlock = allSources.length > 0
    ? allSources.map((s, i) => `[${i + 1}] ${s.title} — ${s.snippet || ''}\nURL: ${s.url}\nDomain: ${s.domain}${s.authoritative ? ' (Authoritative)' : ''}`).join('\n\n')
    : 'No verified sources found.'
  const prompt = `Revise your answer using the verified sources below.
- Cite inline with [1], [2] matching the SOURCE list numbers
- If a claim is unsupported by sources, weaken or remove it
- If sources contradict, note the discrepancy
- Preserve your original structure and tone
- Return ONLY the revised answer (no <thinking> tags)

VERIFIED SOURCES:
${sourcesBlock}

ORIGINAL ANSWER:
${draftAnswer}`

  const councilProviders = getWorkingProviders().filter(p => !['groq', 'openrouter'].includes(p)).slice(0, 2)
  
  const results = await Promise.allSettled(councilProviders.map(p => 
    getAiResponseWithTimeout(p, [
      {role: 'system', content: sysContent},
      {role: 'user', content: prompt}
    ], {temperature: 0.3}, 15000)
  ))
  
  const best = results.find(r => r.status === 'fulfilled' && r.value)?.value
  return best || draftAnswer
}

const AI_DISCLAIMER = '\n\n---\n*This response was generated by the McPherson AI Council. AI-generated content should be verified for critical decisions.*'

const VERIFICATION_CONFIG = {
  maxClaimsPerAnswer: 5,
  maxSourcesPerClaim: 3,
  minConfidenceForClaim: 0.7,
  enableVerification: true,
}

async function extractClaimsFromAnswer(answer) {
  if (!answer || typeof answer !== 'string') return []
  const sentences = answer.split(/[.!?]+/).filter(s => s.trim().length > 20)
  const claims = []
  for (const sentence of sentences) {
    if (/^(I think|I believe|In my opinion|It seems|Perhaps|Maybe)/i.test(sentence.trim())) continue
    if (/^(Note|Remember|However|Therefore|Thus|In conclusion|Summary)/i.test(sentence.trim())) continue
    if (/^(The|This|That|These|Those|It|He|She|They|We|You|A|An|One|Two|Three|Four|Five|According to|Studies show|Research shows|Data shows|Reports indicate)/i.test(sentence.trim())) {
      claims.push(sentence.trim())
    }
  }
  return [...new Set(claims)].slice(0, VERIFICATION_CONFIG.maxClaimsPerAnswer)
}

async function verifyClaims(claims) {
  if (!claims.length || !VERIFICATION_CONFIG.enableVerification) {
    return claims.map(c => ({ claim: c, verified: null, sources: [], confidence: 0 }))
  }
  try {
    const searchResults = await searchForVerification(claims, VERIFICATION_CONFIG.maxSourcesPerClaim)
    const verifiedClaims = []
    for (const claim of claims) {
      const sources = searchResults[claim] || []
      const authoritativeCount = sources.filter(s => s.authoritative).length
      const totalSources = sources.length
      const confidence = totalSources > 0 
        ? Math.min(0.9, (authoritativeCount / Math.max(1, totalSources)) * 0.7 + (totalSources / VERIFICATION_CONFIG.maxSourcesPerClaim) * 0.3)
        : 0
      const verified = confidence >= VERIFICATION_CONFIG.minConfidenceForClaim && authoritativeCount > 0
      verifiedClaims.push({
        claim,
        verified,
        sources: sources.map(s => ({
          citationId: s.citationId,
          title: s.title,
          snippet: s.snippet,
          url: s.url,
          domain: s.domain,
          authoritative: s.authoritative
        })),
        confidence: Math.round(confidence * 100) / 100
      })
    }
    return verifiedClaims
  } catch (err) {
    console.error('Verification error:', err.message)
    return claims.map(c => ({ claim: c, verified: null, sources: [], confidence: 0 }))
  }
}

function formatVerificationBlock(verifiedClaims) {
  if (!verifiedClaims.length) return ''
  const verified = verifiedClaims.filter(v => v.verified).length
  const total = verifiedClaims.length
  const lines = [
    '\n\n---\n',
    `## ✅ Verification Summary`,
    `**${verified}/${total} claims verified** against authoritative sources.\n`
  ]
  for (const vc of verifiedClaims) {
    const status = vc.verified ? '✅ Verified' : vc.confidence > 0 ? '⚠️ Partial' : '❌ Unverified'
    lines.push(`- ${status}: "${vc.claim.slice(0, 100)}${vc.claim.length > 100 ? '...' : ''}"`)
    if (vc.sources.length > 0) {
      lines.push(`  Sources: ${vc.sources.map(s => `[${s.citationId}] ${s.domain}${s.authoritative ? ' ★' : ''}`).join(', ')}`)
    }
  }
  lines.push('\n*Sources cited inline as [n] refer to the verification summary above.*\n')
  return lines.join('\n')
}

function needsVerification(query) {
  const triggers = /\b(latest|current|recent|202\d|best|top|how many|what is|who is|compare|vs\.?|statistics|data|report|price|stock|weather|score|result)\b/i
  return triggers.test(query) || query.length > 150
}

const PREMIUM_SYSTEM_INSTRUCTION = 'You are an elite AI assistant — direct, authoritative, and intellectually rigorous. Follow these rules strictly:\n\n' +
  '## TONE & STRUCTURE\n' +
  '- Be direct and authoritative. No filler introductions or robotic conclusions like "In conclusion" or "As an AI model."\n' +
  '- Open with a confident, direct answer. Then develop with flowing prose and purposeful sections.\n' +
  '- Use ## headings for major topic shifts, --- between major sections.\n' +
  '- Use **bold** for key terms, bullet points only for enumerations.\n' +
  '- Close with a brief synthesis or broader context.\n\n' +
  '## MATHEMATICS\n' +
  '- Always use LaTeX for math formatting. Wrap inline math in $...$ and block equations in $$...$$.\n' +
  '- Always include the constant of integration (+ C) for indefinite integrals.\n' +
  '- Fractions, limits, integrals must stack vertically. Give each algebraic step its own line.\n\n' +
  '## EXAMPLES\n' +
  '- Never explain a complex concept without providing a concrete, brief example.\n\n' +
  '## FORMATTING\n' +
  '- Use Markdown headings (##, ###), bullet points, and tables to structure answers for scannability.\n' +
  '- Wrap code in triple-backtick fences with explicit language identifier (```python, ```sql, ```javascript).\n\n' +
  '## CRITICAL — Must Follow\n' +
  'Start with <thinking>Your step-by-step reasoning — explore nuances, consider edge cases, state assumptions</thinking> then your comprehensive answer.'

const PREMIUM_TURBO_INSTRUCTION = PREMIUM_SYSTEM_INSTRUCTION + '\n\n## TURBO MODE\nOptimize for speed without sacrificing quality. Be concise but complete.'

const PREMIUM_COUNCIL_INSTRUCTION = `You are a fellow expert on the McPherson AI Council — a distinguished academic body.

## Response Rules
- Think thoroughly using <thinking> tags — explore nuances, consider edge cases, state assumptions
- Deliver your answer in <answer> tags — comprehensive, scholarly, with deep explanations and structured sections
- Write in flowing, well-crafted prose with purposeful structure
- Open with context, develop your reasoning, close with synthesis

## Formatting
Use formal LaTeX: $...$ for inline math, $$...$$ for standalone equations.
Fractions, limits, integrals must stack vertically. Give each algebraic step its own line.
Use ## headings, **bold** for key terms, bullet points only for lists.
Use Markdown tables for tabular data. Wrap code in triple-backtick fences with language identifier.

## Tone
Warm but authoritative. Intellectually honest — acknowledge uncertainty when appropriate.
Be thorough: explore real-world examples, historical context, and practical implications.`

const FASTEST_PROVIDERS = ['groq', 'openrouter', 'mistral-large', 'llama', 'llama-3.3', 'phi4', 'deepseek', 'deepseek-v4-flash', 'deepseek-v4-pro', 'mistral-nemotron', 'mistral-nemotron-2', 'nemotron-nano', 'nemotron-nano-8b', 'gemma-4', 'diffusiongemma', 'nemotron-ultra', 'nemotron-super-120b', 'nemotron-super-49b-v15', 'nemotron-super-49b-v1', 'z-ai', 'gpt-oss-20b', 'gpt-oss-120b', 'minimax', 'stepfun', 'kimi', 'inkling', 'poolside']

const providerHealth = new Map()

function getWorkingProviders() {
  const avail = getAvailableProviders()
  const prioritized = [...FASTEST_PROVIDERS.filter(p => avail.includes(p)), ...avail.filter(p => !FASTEST_PROVIDERS.includes(p))]
  return prioritized.filter(p => providerHealth.get(p) !== false)
}

function markProvider(provider, success) {
  if (success) {
    providerHealth.set(provider, true)
  } else {
    const current = providerHealth.get(provider)
    if (current === undefined) providerHealth.set(provider, false)
    else if (current === false) {}
    else providerHealth.set(provider, false)
  }
}

async function getAiResponseWithTimeout(provider, messages, options = {}, timeoutMs = 15000, signal = null) {
  for (let attempt = 0; attempt < 2; attempt++) {
    if (signal?.aborted) return null
    try {
      const result = await Promise.race([
        getAiResponse(provider, messages, { ...options, signal }),
        new Promise(resolve => setTimeout(() => resolve(null), timeoutMs))
      ])
      if (result) {
        markProvider(provider, true)
        return result
      }
    } catch (err) {
      if (err?.authError) {
        markProvider(provider, false)
        return null
      }
    }
    if (signal?.aborted) return null
    if (attempt < 1) await new Promise(r => setTimeout(r, 300))
  }
  markProvider(provider, false)
  return null
}

function isProviderOffline(provider) {
  return providerHealth.get(provider) === false
}

async function executeSearchTools(text, maxRounds = 2) {
  let current = text
  for (let round = 0; round < maxRounds; round++) {
    const searchMatch = current.match(/<web_search>([\s\S]*?)<\/web_search>/i)
    const imgGenMatch = current.match(/<generate_image>([\s\S]*?)<\/generate_image>/i)
    const imgSearchMatch = current.match(/<search_images>([\s\S]*?)<\/search_images>/i)
    
    if (!searchMatch && !imgGenMatch && !imgSearchMatch) break

    if (searchMatch) {
      const q = searchMatch[1].trim()
      const results = await webSearch(q, 5)
      let contextBlock
      if (results.length > 0) {
        contextBlock = `\n\n--- WEB SEARCH RESULTS for "${q}" ---\n${results.map((r, i) => `[${i + 1}] ${r.title}\n${r.snippet}\nURL: ${r.url}`).join('\n\n')}\n--- END WEB SEARCH RESULTS ---`
      } else {
        contextBlock = `\n\n--- WEB SEARCH for "${q}" returned no results. ---`
      }
      current = current.replace(searchMatch[0], `[Web search performed for: "${q}"]${contextBlock}`)
    }

    if (imgGenMatch) {
      const prompt = imgGenMatch[1].trim()
      const result = await generateImage(prompt)
      let replacement
      if (result.url) {
        replacement = `\n\n![Generated Image: ${prompt}](${result.url})\n*Image generated by ${result.provider}*\n`
      } else {
        const imgResults = await searchImages(prompt, 3)
        if (imgResults.length > 0) {
          replacement = `\n\n--- IMAGES FOUND for "${prompt}" ---\n${imgResults.map((r, i) => `[${i + 1}] ${r.title || 'Image'} ${r.url || r.src}`).join('\n')}\n--- END IMAGES ---\n`
        } else {
          replacement = `\n\n[Could not generate or find image for: "${prompt}"]\n`
        }
      }
      current = current.replace(imgGenMatch[0], replacement)
    }

    if (imgSearchMatch) {
      const q = imgSearchMatch[1].trim()
      const results = await searchImages(q, 5)
      let contextBlock
      if (results.length > 0) {
        contextBlock = `\n\n--- IMAGE SEARCH RESULTS for "${q}" ---\n${results.map((r, i) => `[${i + 1}] ${r.title || 'Image'} ${r.url || r.src}`).join('\n')}\n--- END IMAGE SEARCH RESULTS ---`
      } else {
        contextBlock = `\n\n--- IMAGE SEARCH for "${q}" returned no results. ---`
      }
      current = current.replace(imgSearchMatch[0], `[Image search performed for: "${q}"]${contextBlock}`)
    }
  }
  return current
}

// ── Query router: heuristic, not an LLM call. Errs toward "simple" only when confident.
const SIMPLE_QUERY_PATTERNS = /^(what is|what are|who is|who was|when (is|was|did)|where is|define|definition of|give (me )?(the )?formula|list|name|how many|how much|state|which of)\b/i
const COMPLEX_SIGNAL_WORDS = /\b(explain in detail|compare|contrast|analyze|analyse|discuss|derive|prove|evaluate|critique|essay|why does|why is|how does .* work|pros and cons|advantages and disadvantages|step[- ]by[- ]step|walk me through)\b/i

function isSimpleQuery(text) {
  if (!text || typeof text !== 'string') return false
  const trimmed = text.trim()
  if (trimmed.length > 180) return false
  if (COMPLEX_SIGNAL_WORDS.test(trimmed)) return false
  if (SIMPLE_QUERY_PATTERNS.test(trimmed)) return true
  const sentenceCount = (trimmed.match(/[.!?]+/g) || []).length
  return trimmed.length < 90 && sentenceCount <= 1
}

function fallbackResponse(messages) {
  const lastUser = messages.filter(m => m.role === 'user').slice(-1)[0]
  const q = lastUser?.content || 'your question'
  return {
    final: `I appreciate your question about "${q.slice(0, 100)}". I'm currently unable to generate a full response as my AI providers are temporarily unavailable. Please try again in a moment — I'll be happy to help once the connection is restored.`,
    council: [{ provider: 'fallback', thinking: 'All providers unavailable', answer: 'Fallback response' }],
    finalThinking: 'Primary and backup AI providers were unreachable. Sent fallback message.',
    followUps: ['Can you try asking again?', 'Is there another topic I can help with?'],
  }
}

async function aiChat(messages, options = {}) {
  let { fastMode, turboMode, gemPrompt, memoryContext, jsonMode } = options

  // Router: auto-route simple lookups to fast single-provider path instead of full council
  if (!turboMode && !fastMode && !options.forceCouncil) {
    const lastUserMsg = messages.filter(m => m.role === 'user').slice(-1)[0]?.content || ''
    if (isSimpleQuery(lastUserMsg)) {
      turboMode = true
    }
  }

  // Cache lookup
  const cacheKey = (!gemPrompt && !memoryContext) ? buildCacheKey(messages, { turboMode, jsonMode }) : null
  if (cacheKey) {
    const cached = getCachedAnswer(cacheKey)
    if (cached) return { ...cached, cached: true }
  }

  // Inject gem and memory context
  if (gemPrompt || memoryContext) {
    const systemIdx = messages.findLastIndex(m => m.role === 'system')
    if (systemIdx !== -1) {
      let extra = ''
      if (gemPrompt) extra += `\n\n${gemPrompt}`
      if (memoryContext) extra += memoryContext
      messages[systemIdx] = { ...messages[systemIdx], content: messages[systemIdx].content + extra }
    }
  }

  if (process.env.AI_SAFE_MODE === 'true') {
    console.log('[AI SAFE MODE] Bypassing AI Council calls')
    return {
      final: 'This is a simulated response from the McPherson AI Council. [AI_SAFE_MODE is enabled]',
      council: [{ provider: 'safe-mode', thinking: 'Simulated', answer: 'Simulated council response.' }],
      finalThinking: 'Bypassed — AI_SAFE_MODE enabled',
      followUps: [],
    }
  }

  // ── TURBO MODE: fastest single response, no council ──
  if (turboMode) {
    const providers = getWorkingProviders()
    if (providers.length === 0) return fallbackResponse(messages)
    const top = providers.slice(0, 1)
    const sysContent = jsonMode
      ? 'You are a helpful assistant. Return ONLY valid JSON matching the requested schema. No explanatory text, no markdown, no code fences.'
      : 'You are a senior technical instructor with exceptional clarity, delivering textbook-grade responses.\n\n## Response Structure\n1. Open with a direct, confident answer to the question\n2. Develop your explanation with flowing prose and purposeful sections\n3. Use ## headings for major topic shifts, --- between major sections\n4. Use **bold** for key terms, bullet points only for enumerations\n5. Close with a brief synthesis or broader context\n\n## Mathematics\nUse formal LaTeX: wrap inline variables/small formulas in $...$ (e.g., $E = mc^2$, $f(x) = \\lim_{x \\to a} f(x)$).\nPut standalone equations and multi-step derivations in $$...$$ on their own lines.\nFractions, limits, integrals must stack vertically. Give each algebraic step its own line.\n\n## Code\nWrap code in ``` fences with explicit language identifier (```python, ```sql, ```javascript).\n\n## Tabular Data\nUse Markdown tables for comparisons, metrics, properties.\n\n## Tone\nDirect, objective, instructional. Avoid conversational filler.\n\n## CRITICAL — Must Follow\nStart with <thinking>Your step-by-step reasoning — explore nuances, consider edge cases, state assumptions</thinking> then your comprehensive answer.'
    const responses = await Promise.allSettled(top.map(p =>
      getAiResponseWithTimeout(p, [
        { role: 'system', content: sysContent },
        ...messages.slice(-2),
      ], { temperature: jsonMode ? 0.1 : 0.3, json: jsonMode }, 6000)
    ))
    for (const r of responses) {
      if (r.status === 'fulfilled' && r.value) {
        const parsed = extractThinkingAndAnswer(r.value)
        const finalAnswer = (parsed.answer || r.value).trim() + AI_DISCLAIMER
        const result = {
          final: finalAnswer,
          council: [{ provider: 'turbo', thinking: parsed.thinking || 'Fast response', answer: parsed.answer || r.value }],
          finalThinking: parsed.thinking || '',
          followUps: [],
        }
        setCachedAnswer(cacheKey, result)
        return result
      }
    }
    return fallbackResponse(messages)
  }

  const providers = getWorkingProviders()
  if (providers.length === 0) return fallbackResponse(messages)

  // ── Fast provider: always included as a council member ──
  const fastProvider = providers.find(p => FASTEST_PROVIDERS.includes(p)) || providers[0]
  const councilProviders = providers.filter(p => p !== fastProvider)

  const round1Timeout = fastMode ? 12000 : 20000
  const targetResponses = fastMode ? 2 : Math.min(3, councilProviders.length + 1)

  let preSearchContext = ''

  const searchCapablePrompt = `\n\nYou have LIVE WEB SEARCH access. Use <web_search>query</web_search> inside your <answer> tags to search.`

  const answers = []
  const round1Controller = new AbortController()

  // Kick off fast provider in parallel
  const fastPromise = (async () => {
    const fastMessages = [
      { role: 'system', content: 'You are a senior technical instructor with exceptional clarity, delivering textbook-grade responses.\n\n## Response Rules\n- Open with a direct, confident answer to the question\n- Develop your explanation with flowing prose and purposeful sections\n- Use ## headings for major topic shifts, --- between major sections\n- Use **bold** for key terms, bullet points only for enumerations\n- Close with a brief synthesis or broader context\n\n## Formatting\nUse formal LaTeX: $...$ for inline math, $$...$$ for standalone equations.\nFractions, limits, integrals must stack vertically. Give each algebraic step its own line.\nUse ## headings, **bold** for key terms, bullet points only for lists.\nUse Markdown tables for tabular data. Wrap code in ``` fences with language identifier.\n\n## Tone\nDirect, objective, instructional. Avoid conversational filler.\n\n## CRITICAL — Must Follow\nStart with <thinking>Your step-by-step reasoning — explore nuances, consider edge cases, state assumptions</thinking> then your comprehensive answer.' },
      ...messages.slice(-2),
    ]
    const resp = await getAiResponseWithTimeout(fastProvider, fastMessages, { temperature: 0.3 }, 8000, round1Controller.signal)
    if (resp) {
      const parsed = extractThinkingAndAnswer(resp)
      answers.push({ provider: fastProvider, thinking: parsed.thinking || 'Fast response', answer: parsed.answer || resp })
    }
  })()

  // Council providers (all except the fast one)
  const promises = councilProviders.map(async (p) => {
    const roleInstruction = specialistRoles[p] || 'You are a PRO-LEVEL academic consultant.'
    const cotMessages = [
      { role: 'system', content: `${roleInstruction}\nYou are a fellow expert on the McPherson AI Council — a distinguished academic body.\n\n## Response Rules\n- Think thoroughly using <thinking> tags — explore nuances, consider edge cases, state assumptions\n- Deliver your answer in <answer> tags — comprehensive, scholarly, with deep explanations and structured sections\n- Write in flowing, well-crafted prose with purposeful structure\n- Open with context, develop your reasoning, close with synthesis\n\n## Formatting\nUse formal LaTeX: $...$ for inline math, $$...$$ for standalone equations.\nFractions, limits, integrals must stack vertically. Give each algebraic step its own line.\nUse ## headings, **bold** for key terms, bullet points only for lists.\nUse Markdown tables for tabular data. Wrap code in \`\`\` fences with language identifier.\n\n## Tone\nWarm but authoritative. Intellectually honest — acknowledge uncertainty when appropriate.\nBe thorough: explore real-world examples, historical context, and practical implications.${searchCapablePrompt}` },
      ...messages,
      ...(preSearchContext ? [{ role: 'system', content: preSearchContext }] : []),
    ]

    const resp = await getAiResponseWithTimeout(p, cotMessages, { temperature: 0.35 }, round1Timeout, round1Controller.signal)
    if (resp) {
      const withSearch = await executeSearchTools(resp)
      const parsed = extractThinkingAndAnswer(withSearch)
      answers.push({ provider: p, thinking: parsed.thinking, answer: parsed.answer })
      if (answers.length >= targetResponses) return true
    }
    return false
  })

  await Promise.race([
    Promise.allSettled([fastPromise, ...promises]),
    new Promise(resolve => {
      const checker = setInterval(() => {
        if (answers.length >= targetResponses) {
          clearInterval(checker)
          resolve()
        }
      }, 100)
      setTimeout(() => { clearInterval(checker); resolve() }, round1Timeout)
    })
  ])

  // Cancel all still-running provider calls now that quorum is reached
  round1Controller.abort()

  if (answers.length === 0) return fallbackResponse(messages)
  if (answers.length === 1) {
    const final = await executeSearchTools(answers[0].answer)
    const followUps = await generateFollowUps(messages, final)
    const result = { final: (final || answers[0].answer || 'I was unable to generate a response.') + AI_DISCLAIMER, council: [{ ...answers[0], answer: final }], finalThinking: answers[0].thinking, followUps }
    setCachedAnswer(cacheKey, result)
    return result
  }

  // ── Cross-judge: each expert critiques another expert's answer ──
  const crossJudgments = []
  const crossJudgmentPromises = answers.map((_, i) => {
    const targetIdx = (i + 1) % answers.length
    const judgeProvider = answers[i].provider
    const targetProvider = answers[targetIdx].provider
    const critiquePrompt = [
      { role: 'system', content: `You are a PEER REVIEWER on the McPherson AI Council. Critique the following answer from ${targetProvider} with scholarly rigor. Identify strengths, weaknesses, factual errors, and areas for deeper analysis. Provide your detailed critique in <thinking> tags, then an enhanced/revised answer in <answer> tags that is comprehensive, well-structured, and academically thorough. Use LaTeX for all math ($...$ inline, $$...$$ display).` },
      { role: 'user', content: `Expert ${targetProvider}'s answer:\n\n<thinking>${answers[targetIdx].thinking || 'No reasoning'}</thinking>\n<answer>${answers[targetIdx].answer}</answer>` }
    ]
    return getAiResponseWithTimeout(judgeProvider, critiquePrompt, { temperature: 0.3 }, 15000).then(critique => {
      if (critique) {
        const parsed = extractThinkingAndAnswer(critique)
        crossJudgments.push({ judge: judgeProvider, target: targetProvider, critique: parsed.thinking, revisedAnswer: parsed.answer })
      }
    })
  })
  await Promise.allSettled(crossJudgmentPromises)

  const councilPrompt = [
    ...messages,
    {
      role: 'system',
      content: `### SUPREME COUNCIL VERDICT ###
You are the CHIEF JUSTICE of the McPherson AI Council — a distinguished scholar synthesizing expert opinions.
Synthesize the ${answers.length} expert testimonies and their peer reviews below into a SINGLE comprehensive, scholarly verdict.
Use LaTeX for all math: $...$ inline, $$...$$ display.

ALL EXPERT TESTIMONIES:
${answers.map((a, i) => `\n[EXPERT ${i + 1} - ${a.provider}]:\n<thinking>${a.thinking || 'No reasoning'}</thinking>\n<answer>${a.answer}</answer>`).join('\n')}

PEER REVIEWS:
${crossJudgments.map(c => `\n[${c.judge} reviews ${c.target}]:\n<critique>${c.critique || 'No critique'}</critique>\n<revised>${c.revisedAnswer || 'No revision'}</revised>`).join('\n') || 'No peer reviews available.'}

Provide your judicial reasoning in <thinking> tags — weigh evidence, reconcile conflicts, note consensus areas.
Then deliver your final verdict in <answer> tags — a comprehensive, well-structured scholarly synthesis that opens with the key conclusion, develops supporting evidence, and closes with broader implications.`
    }
  ]

  const deepseekAvail = providers.includes('deepseek')
  const nemotronUltraAvail = providers.includes('nemotron-ultra')
  const kimiAvail = providers.includes('kimi')
  const judgeProviders = []
  if (nemotronUltraAvail) judgeProviders.push('nemotron-ultra')
  if (kimiAvail) judgeProviders.push('kimi')
  if (deepseekAvail) judgeProviders.push('deepseek')
  judgeProviders.push('mistral-large')

  const judgePromises = judgeProviders.map(p =>
    getAiResponseWithTimeout(p, councilPrompt, { temperature: 0.2 }, fastMode ? 15000 : 25000)
  )

  const judgeResults = await Promise.allSettled(judgePromises)
  const verdicts = judgeResults.filter(r => r.status === 'fulfilled' && r.value).map(r => r.value)

  let finalThinking = null
  let finalAnswer = answers[0].answer
  let secondaryVerdict = null

  if (verdicts.length > 0) {
    const bestVerdict = verdicts[0]
    const parsed = extractThinkingAndAnswer(await executeSearchTools(bestVerdict))
    finalThinking = parsed.thinking
    finalAnswer = parsed.answer

    if (verdicts.length > 1) {
      const dParsed = extractThinkingAndAnswer(verdicts[1])
      secondaryVerdict = { judge: judgeProviders[1] || 'secondary', answer: dParsed.answer }
    }
  }

  const followUps = await generateFollowUps(messages, finalAnswer)

  // 🔍 VERIFICATION
  const userQuery = messages.find(m => m.role === 'user')?.content || ''
  const verificationMode = (options.verifyWithSearch !== false && needsVerification(userQuery)) ? 'council' : false
  
  let verificationData = null
  if (verificationMode && finalAnswer) {
    try {
      const claims = await extractClaims(finalAnswer)
      if (claims.length > 0) {
        const vData = await verifyClaims(claims)
        const revised = await reviseWithCitations(finalAnswer, vData, messages)
        finalAnswer = revised
        finalThinking = (finalThinking || '') + '\n\n✅ Verified against web sources.'
        verificationData = vData
      }
    } catch (e) {
      console.warn('Verification failed:', e.message)
    }
  }

  const finalContent = finalAnswer || answers[0]?.answer || 'I was unable to generate a complete response. Please try rephrasing your question.'
  const result = { final: finalContent + AI_DISCLAIMER, council: answers, finalThinking, followUps, verificationData, secondaryVerdict }
  setCachedAnswer(cacheKey, result)
  return result
}

async function generateFollowUps(messages, response) {
  try {
    const providers = getAvailableProviders()
    const fp = ['groq', 'openrouter', 'mistral-large'].find(p => providers.includes(p))
    if (!fp) return []

    const prompt = [
      { role: 'system', content: 'Based on the conversation, generate 3 follow-up questions the user might ask next. Return ONLY a JSON array of 3 strings, each 5-12 words. Example: ["What is the derivative of x²?", "Can you show more examples?"]' },
      { role: 'user', content: `Conversation:\n${messages.slice(-2).map(m => `${m.role}: ${m.content.slice(0, 200)}`).join('\n')}\n\nAI Response: ${response.slice(0, 500)}\n\nGenerate 3 follow-up questions. Return ONLY the JSON array.` }
    ]

    const resp = await Promise.race([
      getAiResponse(fp, prompt, { temperature: 0.4, json: true }),
      new Promise(resolve => setTimeout(() => resolve(null), 4000))
    ])

    if (!resp) return []
    const parsed = typeof resp === 'string' ? JSON.parse(resp) : resp
    if (!Array.isArray(parsed)) return []
    return parsed.slice(0, 3).map(q => typeof q === 'string' ? q : String(q))
  } catch {
    return []
  }
}

function extractThinkingAndAnswer(text) {
  let thinking = null
  let answer = text
  const thinkMatch = text.match(/<thinking>([\s\S]*?)<\/thinking>/i)
  if (thinkMatch) {
    thinking = thinkMatch[1].trim()
    answer = text.replace(/<thinking>[\s\S]*?<\/thinking>/gi, '').trim()
    answer = answer.replace(/<\/?answer>/gi, '').trim()
  }
  return { thinking, answer }
}

async function generateChatTitle(convId, userId, userQuestion, aiResponse) {
  try {
    const providers = getAvailableProviders()
    if (!providers.length) return
    const titlePrompt = [
      { role: 'system', content: 'Generate a very short title (3-6 words max) for a chat conversation. Return ONLY the title, no quotes, no punctuation.' },
      { role: 'user', content: `Question: ${userQuestion.slice(0, 300)}\n\nResponse: ${aiResponse.slice(0, 500)}` },
    ]
    const p = providers.includes('groq') ? 'groq' : providers[0]
    const title = await getAiResponseWithTimeout(p, titlePrompt, { temperature: 0.3 }, 5000)
    if (title && title.trim().length > 0 && title.trim().length < 80) {
      await query(
        `UPDATE public.chat_conversations SET title = $1 WHERE id = $2 AND user_id = $3`,
        [title.trim(), convId, userId]
      )
    }
  } catch { }
}

async function transcribeAudio(buffer, fileName, mimeType) {
  if (!buffer) return null

  const whisperClient = getAI('openai')
  if (whisperClient) {
    try {
      const transcription = await whisperClient.audio.transcriptions.create({
        file: await whisperClient.toFile(buffer, fileName),
        model: 'whisper-1',
      })
      return transcription.text
    } catch (err) {
      console.error('OpenAI Whisper error:', err.message)
    }
  }

  const keys = [
    { key: process.env.NVIDIA_WHISPER_KEY, model: 'nvidia/whisper-large-v3' },
    { key: process.env.NVIDIA_NEMOTRON_KEY, model: 'nvidia/nemotron-asr-streaming' },
  ]

  for (const { key, model } of keys) {
    if (!key) continue
    try {
      const blob = new Blob([buffer], { type: mimeType })
      const form = new FormData()
      form.append('audio', blob, fileName)
      form.append('model', model)
      const res = await fetch('https://integrate.api.nvidia.com/v1/audio/transcriptions', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${key}` },
        body: form,
      })
      if (!res.ok) continue
      const data = await res.json()
      if (data.text) return data.text
    } catch { }
  }
  return null
}

export { executeSearchTools, aiChat, extractThinkingAndAnswer, generateChatTitle, transcribeAudio, generateFollowUps }
